# Generated by Django 5.1.3 on 2024-11-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsystem_app', '0002_housedetails_society_buyer_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetails',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='smsystem_app.society'),
        ),
    ]
