# Generated by Django 5.1.3 on 2024-12-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsystem_app', '0003_housedetails_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetails',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='smsystem_app.seller'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsystem_app.buyer')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsystem_app.housedetails')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsystem_app.seller')),
            ],
        ),
    ]
