# Generated by Django 5.1.3 on 2024-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsystem_app', '0007_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected')], max_length=20, null=True),
        ),
    ]
